const paragraphs = [
    "Typing is the process of writing or inputting text by pressing keys on a typewriter, computer keyboard, cell phone, or calculator. It can be distinguished from other means of text input, such as handwriting and speech recognition. Text can be in the form of letters, numbers and other symbols. The world's first typist was Lillian Sholes from Wisconsin, the daughter of Christopher Sholes, who invented the first practical typewriter. User interface features such as spell checker and autocomplete serve to facilitate and speed up typing and to prevent or correct errors the typist may make.",

    "Hunt and peck (two-fingered typing) is a common form of typing in which the typist presses each key individually. Instead of relying on the memorized position of keys, the typist must find each key by sight. Although good accuracy may be achieved, the use of this method may also prevent the typist from being able to see what has been typed without glancing away from the keys, and any typing errors that are made may not be noticed immediately. Because only a few fingers are used in this technique, this also means that the fingers are forced to move a much greater distance.",

    "Touch Typing technique, the typist keeps their eyes on the source copy at all times. Touch typing also involves the use of the home row method, where typists rest their wrist down, rather than lifting up and typing (which can cause carpal tunnel syndrome). To avoid this, typists should sit up tall, leaning slightly forward from the waist, place their feet flat on the floor in front of them with one foot slightly in front of the other, and keep their elbows close to their sides with forearms slanted slightly upward to the keyboard; fingers should be curved slightly and rest on the home row.",

    "Many touch typists also use keyboard shortcuts when typing on a computer. This allows them to edit their document without having to take their hands off the keyboard to use a mouse. An example of a keyboard shortcut is pressing the Ctrl key + S key to save a document as they type, or the Ctrl key + Z key to undo a mistake. Other shortcuts are the Ctrl key + C to copy and the Ctrl key + V key to paste, and the Ctrl key + X key to cut. Many experienced typists can feel or sense when they have made an error and can hit the Backspace key and make the correction with no increase in time between keystrokes.",

    "Hybrid. There are many idiosyncratic typing styles in between novice-style hunt and peck and touch typing. For example, many hunt and peck typists have the keyboard layout memorized and are able to type while focusing their gaze on the screen. Some use just two fingers, while others use 3 – 6 fingers. Some use their fingers very consistently, with the same finger being used to type the same character every time, while others vary the way they use their fingers.",

    "One study examining 30 subjects, of varying different styles and expertise, has found minimal difference in typing speed between touch typists and self-taught hybrid typists. According to the study, The number of fingers does not determine typing speed... People using self-taught typing strategies were found to be as fast as trained typists... instead of the number of fingers, there are other factors that predict typing speed... fast typists... keep their hands fixed on one position, instead of moving them over the keyboard, and more consistently use the same finger to type a certain letter.",

    "Thumbing A late 20th century trend in typing, primarily used with devices with small keyboards (such as PDAs and Smartphones), is thumbing or thumb typing. This can be accomplished using either only one thumb or both the thumbs, with more proficient typists reaching speeds of 100 words per minute. Similar to desktop keyboards and input devices, if a user overuses keys which need hard presses and/or have small and unergonomic layouts, it could cause thumb tendonitis or other repetitive strain injury.",

    "Words per minute (WPM) is a measure of typing speed, commonly used in recruitment. For the purposes of WPM measurement a word is standardized to five characters or keystrokes. Therefore, 'brown' counts as one word, but 'mozzarella' counts as two. The benefits of a standardized measurement of input speed are that it enables comparison across language and hardware boundaries. The speed of an Afrikaans-speaking operator in Cape Town can be compared with a French-speaking operator in Paris.",

    "A less common measure of the speed of a typist, CPM is used to identify the number of characters typed per minute. This is a common measurement for typing programs, or typing tutors, as it can give a more accurate measure of a person's typing speed without having to type for a prolonged period of time. The common conversion factor between WPM and CPM is 5. It is also used occasionally for associating the speed of a reader with the amount they have read. CPM has also been applied to 20th century printers, but modern faster printers more commonly use PPM (pages per minute).",

    "Keystroke dynamics, or typing dynamics, is the obtaining of detailed timing information that describes exactly when each key was pressed and when it was released as a person is typing at a computer keyboard for biometric identification, similar to speaker recognition. Data needed to analyze keystroke dynamics is obtained by keystroke logging. The behavioral biometric of Keystroke Dynamics uses the manner and rhythm in which an individual types characters on a keyboard or keypad."
];